
title: Compassos - Stúdio de Dança
email: your-email@domain.com
description: >
baseurl: "/comp"
url: "https://heirian.github.io"
twitter_username:
github_username:

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# settings

vacations_time?: true
